import Link from "next/link";
import { notFound } from "next/navigation";
import { AlertTriangle, Bot, Cloud, KeyRound, Plus, RefreshCw, Save, ShieldCheck, UserRound } from "lucide-react";

import { FrameField, FrameSelect } from "@/components/frame-field";
import { ScreenHeader } from "@/components/screen-header";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";

const sections = {
  excluded: { title: "종료·제외 상담", description: "보류·실패·제외 건" },
  audit: { title: "전체 감사 기록", description: "사용자·AI·자동화 이력" },
  users: { title: "사용자·권한", description: "Google Workspace 구성원" },
  vacations: { title: "휴가·자동 위임", description: "새 상담 대체 담당자" },
  ai: { title: "AI 서비스 계정", description: "권한과 승인 정책" },
  integrations: { title: "외부 연동", description: "연결 상태와 장애 채널" },
  services: { title: "서비스·성공 확률", description: "영업 기준값" },
  reliability: { title: "안정성·실패 보관함", description: "재시도·백업·장애" },
} as const;

export function generateStaticParams() { return Object.keys(sections).map((section) => ({ section })); }

export default async function ManagementSectionPage({ params }: { params: Promise<{ section: string }> }) {
  const { section } = await params; const config = sections[section as keyof typeof sections]; if (!config) notFound();
  return <><ScreenHeader title={config.title} description={config.description} backHref="/more" /><div className="space-y-5 px-4 py-5"><ManagementContent section={section as keyof typeof sections} /></div></>;
}

function ManagementContent({ section }: { section: keyof typeof sections }) {
  if (section === "excluded") return <><div className="grid grid-cols-3 gap-2">{[["장기 보류", "4"], ["계약 실패", "7"], ["상담 제외", "3"]].map(([label, value]) => <Card key={label} className="py-4"><CardContent className="px-3 text-center"><p className="text-xl font-bold">{value}</p><p className="mt-1 text-xs text-muted-foreground">{label}</p></CardContent></Card>)}</div>{[["한성바이오", "장기 보류", "92일 무활동"], ["좋은교육연구소", "상담 제외", "서비스 내용 오인"], ["에버핀", "계약 실패", "예산 미확보"]].map(([company, status, reason]) => <Card key={company} className="py-4"><CardContent className="space-y-3 px-4"><div className="flex justify-between"><div><Badge variant="secondary">{status}</Badge><p className="mt-2 font-semibold">{company}</p><p className="mt-1 text-xs text-muted-foreground">{reason}</p></div><Button variant="outline" size="sm">재활성화</Button></div></CardContent></Card>)}</>;
  if (section === "audit") return <><div className="grid grid-cols-2 gap-2"><Button variant="outline">전체 행위자</Button><Button variant="outline">전체 데이터</Button></div><Card><CardContent className="space-y-5">{[["김정석", "계약 금액 수정", "다원그룹 · 5,400만원 → 5,600만원", "오늘 오후 2:32"], ["AI 영업 에이전트", "승인 요청 생성", "계산서 발행일 변경", "오늘 오후 2:10"], ["시스템", "담당자 자동 지정", "한빛모빌리티 → 김정석", "오늘 오전 11:40"]].map(([actor, action, detail, time]) => <div key={time} className="border-l-2 pl-3"><div className="flex justify-between gap-3"><p className="text-sm font-semibold">{action}</p><span className="text-xs text-muted-foreground">{time}</span></div><p className="mt-1 text-sm">{detail}</p><p className="mt-1 text-xs text-muted-foreground">{actor}</p></div>)}</CardContent></Card></>;
  if (section === "users") return <><Button className="w-full"><Plus /> 사용자 초대</Button><Card className="gap-0 py-0"><CardContent className="divide-y px-0">{[["김정석", "kim@truenorthcrew.com", "관리자"], ["대표님", "ceo@truenorthcrew.com", "관리자"], ["운영 담당자", "ops@truenorthcrew.com", "열람자"]].map(([name, email, role]) => <div key={email} className="flex items-center gap-3 px-4 py-4"><div className="flex size-9 items-center justify-center rounded-full bg-muted"><UserRound className="size-4" /></div><div className="min-w-0 flex-1"><p className="text-sm font-semibold">{name}</p><p className="truncate text-xs text-muted-foreground">{email}</p></div><Badge variant={role === "관리자" ? "default" : "outline"}>{role}</Badge></div>)}</CardContent></Card><Card className="border-dashed"><CardContent className="text-sm leading-6 text-muted-foreground">회사 도메인 사용자는 열람자로 자동 가입됩니다. 열람자는 재무를 포함한 전체 데이터를 볼 수 있지만 수정할 수 없습니다.</CardContent></Card></>;
  if (section === "vacations") return <><Card><CardHeader><div className="flex justify-between"><CardTitle>등록된 휴가</CardTitle><Badge variant="secondary">예정</Badge></div></CardHeader><CardContent className="space-y-3 text-sm"><div className="flex justify-between"><span className="text-muted-foreground">휴가자</span><span>김정석</span></div><div className="flex justify-between"><span className="text-muted-foreground">기간</span><span>9월 2일~6일</span></div><div className="flex justify-between"><span className="text-muted-foreground">대체 담당자</span><span>대표님</span></div><p className="rounded-lg bg-muted p-3 text-xs leading-5 text-muted-foreground">휴가 중 새로 들어온 상담만 자동 위임되며 종료 후에도 대표님이 계속 담당합니다.</p></CardContent></Card><Card><CardHeader><CardTitle>휴가 직접 등록</CardTitle></CardHeader><CardContent className="space-y-4"><FrameField label="휴가자"><FrameSelect value="김정석" /></FrameField><div className="grid grid-cols-2 gap-3"><FrameField label="시작일"><FrameSelect value="9월 2일" /></FrameField><FrameField label="종료일"><FrameSelect value="9월 6일" /></FrameField></div><FrameField label="대체 담당자"><FrameSelect value="대표님" /></FrameField></CardContent></Card><Button className="w-full"><Save /> 휴가 등록</Button></>;
  if (section === "ai") return <><Card><CardHeader><div className="flex justify-between"><div><Badge>활성</Badge><CardTitle className="mt-3">AI 영업 에이전트</CardTitle></div><Bot className="size-6 text-muted-foreground" /></div></CardHeader><CardContent className="space-y-3 text-sm"><div className="flex justify-between"><span className="text-muted-foreground">영업 데이터</span><span>직접 반영</span></div><div className="flex justify-between"><span className="text-muted-foreground">재무 데이터</span><span>승인 필요</span></div><div className="flex justify-between"><span className="text-muted-foreground">마지막 사용</span><span>10분 전</span></div><Button asChild variant="outline" className="w-full"><Link href="/approvals">승인 대기 2건</Link></Button></CardContent></Card><Card><CardHeader><CardTitle>서비스 계정 추가</CardTitle></CardHeader><CardContent className="space-y-4"><FrameField label="계정 이름"><Input placeholder="예: 제안서 분석 에이전트" /></FrameField><FrameField label="권한 범위"><FrameSelect value="영업 조회·활동 작성" /></FrameField><FrameField label="재무 변경"><FrameSelect value="사람 승인 필요" /></FrameField></CardContent></Card><Button className="w-full"><KeyRound /> 계정 발급</Button></>;
  if (section === "integrations") return <><Card className="gap-0 py-0"><CardContent className="divide-y px-0">{[["Emergent 문의 API", "정상", "방금 동기화"], ["Google 로그인", "정상", "자동 갱신"], ["Gmail 발신", "정상", "발신 전용"], ["공휴일 API", "정상", "2026년 반영"], ["장애 Webhook", "설정 필요", "미등록"]].map(([name, status, meta]) => <div key={name} className="flex items-center gap-3 px-4 py-4"><div className="flex size-9 items-center justify-center rounded-md bg-muted"><Cloud className="size-4" /></div><div className="min-w-0 flex-1"><p className="text-sm font-medium">{name}</p><p className="mt-1 text-xs text-muted-foreground">{meta}</p></div><Badge variant={status === "정상" ? "outline" : "secondary"}>{status}</Badge></div>)}</CardContent></Card><Card><CardHeader><CardTitle>장애 알림 채널</CardTitle></CardHeader><CardContent className="space-y-4"><FrameField label="보조 이메일"><Input defaultValue="admin@truenorthcrew.com" /></FrameField><FrameField label="범용 Webhook"><Input placeholder="https://..." /></FrameField><FrameField label="추가 채널"><FrameSelect value="관리자에서 확장 가능" /></FrameField></CardContent></Card><Button className="w-full"><Save /> 연동 설정 저장</Button></>;
  if (section === "services") return <><Card><CardHeader><div className="flex justify-between"><CardTitle>판매 서비스</CardTitle><Button variant="outline" size="sm"><Plus /> 추가</Button></div></CardHeader><CardContent className="space-y-3">{["집합교육", "온라인 1:1 코칭", "AX 구축 서비스", "3개월 변화관리 컨설팅"].map((service) => <div key={service} className="flex items-center justify-between rounded-lg border px-3 py-3"><span className="text-sm font-medium">{service}</span><Badge variant="outline">사용</Badge></div>)}</CardContent></Card><Card><CardHeader><CardTitle>단계별 기본 성공 확률</CardTitle></CardHeader><CardContent className="space-y-3">{[["신규", "0%"], ["초기 상담", "5%"], ["후속 진행", "10%"], ["제안·견적", "20%"], ["협의 중", "40%"], ["계약서 송부", "60%"], ["계약서 서명 완료", "80%"], ["첫 유효 계산서", "100%"]].map(([stage, value]) => <div key={stage} className="flex items-center justify-between text-sm"><span>{stage}</span><Badge variant="secondary">{value}</Badge></div>)}</CardContent></Card><Button className="w-full"><Save /> 기준 저장</Button></>;
  return <><div className="grid grid-cols-2 gap-3">{[["API·배치", "정상"], ["마지막 백업", "오늘 03:00"], ["실패 작업", "2건"], ["복원 시험", "6월 완료"]].map(([label, value]) => <Card key={label} className="py-4"><CardContent className="px-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-bold">{value}</p></CardContent></Card>)}</div><Card><CardHeader><div className="flex justify-between"><CardTitle>실패 보관함</CardTitle><Badge variant="secondary">2건</Badge></div></CardHeader><CardContent className="space-y-4">{[["Emergent 원본 조회", "5회 실패 · 14:05"], ["Gmail 발신", "인증 만료 · 13:40"]].map(([title, meta]) => <div key={title} className="flex items-center gap-3"><AlertTriangle className="size-5 text-muted-foreground" /><div className="flex-1"><p className="text-sm font-medium">{title}</p><p className="text-xs text-muted-foreground">{meta}</p></div><Button variant="outline" size="sm"><RefreshCw /> 재시도</Button></div>)}</CardContent></Card><Card><CardHeader><CardTitle>복구 기준</CardTitle></CardHeader><CardContent className="space-y-3 text-sm">{[["최대 중단 허용", "반나절"], ["허용 데이터 손실", "하루치"], ["재시도", "최대 5회"], ["기록 보관", "계속"]].map(([label, value]) => <div key={label} className="flex justify-between"><span className="text-muted-foreground">{label}</span><span>{value}</span></div>)}</CardContent></Card><Button className="w-full"><ShieldCheck /> 장애 채널 테스트</Button></>;
}
